const movieMockData = [{"id":1,"title":"Profession of Arms, The (Il mestiere delle armi)","genre":"Adventure|Drama|War","director":"Padriac Eickhoff"},
    {"id":2,"title":"Little Traitor, The","genre":"Drama","director":"Berry Melonby"},
    {"id":3,"title":"Minecraft: The Story of Mojang","genre":"Documentary","director":"Lizzy Hennington"},
    {"id":4,"title":"War Is Over, The (Guerre est finie, La)","genre":"Drama","director":"Lion Slite"},
    {"id":5,"title":"How About You...","genre":"Comedy|Drama","director":"Rolf Bainton"},
    {"id":6,"title":"Beyond (Svinalängorna)","genre":"Drama","director":"Carolee Teodori"},
    {"id":7,"title":"Barefoot","genre":"Comedy|Drama|Romance","director":"Iggie Doctor"},
    {"id":8,"title":"My Awkward Sexual Adventure","genre":"Comedy","director":"Dian Pala"},
    {"id":9,"title":"Jay and Silent Bob Go Down Under","genre":"Comedy","director":"Umeko Nock"},
    {"id":10,"title":"Lovely Molly","genre":"Horror","director":"Rosalie Measor"},
    {"id":11,"title":"Rafa","genre":"Drama","director":"Zak Golledge"},
    {"id":12,"title":"Hello Herman","genre":"Drama","director":"Kristi Ferrettino"},
    {"id":13,"title":"El malvado Carabel","genre":"Comedy","director":"Marcy Purvis"},
    {"id":14,"title":"As If I Didn't Exist (Elina - Som om jag inte fanns)","genre":"Children|Drama","director":"Abagail Brydell"},
    {"id":15,"title":"W.","genre":"Drama","director":"Sari Dohmann"},
    {"id":16,"title":"Shiner","genre":"Crime|Drama|Thriller","director":"Nigel Symms"},
    {"id":17,"title":"Arlington Road","genre":"Thriller","director":"Lowrance Coopey"},
    {"id":18,"title":"Nadja","genre":"Drama","director":"Alwin Georgiades"},
    {"id":19,"title":"4 Horsemen of the Apocalypse, The","genre":"Drama","director":"Kendrick Faiers"},
    {"id":20,"title":"Eagle Eye","genre":"Action|Crime|Thriller|IMAX","director":"Ber Hawes"},
    {"id":21,"title":"Macbeth in Manhattan","genre":"Drama","director":"Davis Bloschke"},
    {"id":22,"title":"Eagle vs Shark","genre":"Comedy","director":"Wells Brabon"},
    {"id":23,"title":"Slipstream","genre":"Comedy|Drama|Fantasy|Mystery|Sci-Fi|Thriller","director":"Giovanna Dimblebee"},
    {"id":24,"title":"Marriage Retreat","genre":"Comedy|Drama","director":"Schuyler Monks"},
    {"id":25,"title":"Tipping the Velvet","genre":"Comedy|Drama|Romance","director":"Alexio Shevell"},
    {"id":26,"title":"Darling Companion","genre":"Drama","director":"Allissa Garza"},
    {"id":27,"title":"Day & Night","genre":"Animation|Children","director":"Edwin Daout"},
    {"id":28,"title":"Loving Annabelle","genre":"Drama|Romance","director":"Vittoria Janovsky"},
    {"id":29,"title":"100 Years at the Movies","genre":"Documentary","director":"Perrine Hurst"},
    {"id":30,"title":"Zuzu Angel","genre":"Drama","director":"Roseline Antosik"},
    {"id":31,"title":"LEGO Batman: The Movie - DC Heroes Unite","genre":"Action|Adventure|Animation","director":"Merrill Clifford"},
    {"id":32,"title":"Between Miracles","genre":"Comedy","director":"Ellery Claughton"},
    {"id":33,"title":"Ten Tall Men","genre":"Action|Adventure|Comedy|War","director":"Bobinette Kinnear"},
    {"id":34,"title":"Cat from Outer Space, The","genre":"Children|Comedy|Sci-Fi","director":"Binky Nairy"},
    {"id":35,"title":"The Derby Stallion","genre":"Children|Drama","director":"Carlie Yurkov"},
    {"id":36,"title":"King of California","genre":"Comedy","director":"Vassili Coneron"},
    {"id":37,"title":"Work of Director Michel Gondry, The","genre":"Comedy|Documentary","director":"Vale Gorham"},
    {"id":38,"title":"Merrill's Marauders","genre":"Adventure|Drama|War","director":"Tracy Dumpleton"},
    {"id":39,"title":"Wild Things","genre":"Crime|Drama|Mystery|Thriller","director":"Appolonia Belli"},
    {"id":40,"title":"Bring It On: Fight to the Finish","genre":"Comedy","director":"Terrie Beckworth"},
    {"id":41,"title":"Chill Out! (Descongélate!)","genre":"Comedy|Drama","director":"Broderic Alwell"},
    {"id":42,"title":"Love and Pigeons","genre":"Comedy|Romance","director":"Alia Brettel"},
    {"id":43,"title":"Lady for a Day","genre":"Comedy","director":"Windy Saunton"},
    {"id":44,"title":"The Cobbler","genre":"Comedy|Drama|Fantasy","director":"Albie Greasley"},
    {"id":45,"title":"The Remaining","genre":"Horror|Thriller","director":"Dione Mattingley"},
    {"id":46,"title":"Mondays in the Sun (Lunes al sol, Los)","genre":"Drama","director":"Myrlene Fossick"},
    {"id":47,"title":"Rome, Open City (a.k.a. Open City) (Roma, città aperta)","genre":"Drama|War","director":"Bethina Kienzle"},
    {"id":48,"title":"Piano Teacher, The (La pianiste)","genre":"Drama","director":"Modesty Brandli"},
    {"id":49,"title":"Hard Way, The","genre":"Drama","director":"Arman Berriball"},
    {"id":50,"title":"Hello Ladies: The Movie","genre":"Comedy","director":"Irv Coll"},
    {"id":51,"title":"The Wayward Girl","genre":"Drama","director":"Reeta Palfreeman"},
    {"id":52,"title":"Walk All Over Me","genre":"Comedy|Crime|Drama","director":"Vick Blowfield"},
    {"id":53,"title":"Rebirth of Mothra","genre":"Action|Fantasy|Sci-Fi","director":"Samantha Philippson"},
    {"id":54,"title":"Metal Brothers (Mammas pojkar)","genre":"Comedy","director":"Town Dilley"},
    {"id":55,"title":"What's Love Got to Do with It?","genre":"Drama|Musical","director":"Bea Stucksbury"},
    {"id":56,"title":"Staying Together","genre":"Comedy|Drama","director":"Jenelle Culpan"},
    {"id":57,"title":"As You Like It","genre":"Comedy","director":"Reamonn Shave"},
    {"id":58,"title":"Alan Smithee Film: Burn Hollywood Burn, An","genre":"Comedy","director":"Kelbee Pues"},
    {"id":59,"title":"Brothers (Veljekset)","genre":"Drama","director":"Deane Luparti"},
    {"id":60,"title":"Capture of Bigfoot, The","genre":"Adventure|Horror|Sci-Fi","director":"Marmaduke Basso"},
    {"id":61,"title":"Wonderland","genre":"Drama","director":"Wilbur Sumshon"},
    {"id":62,"title":"Furry Vengeance","genre":"Children|Comedy","director":"Averell McRitchie"},
    {"id":63,"title":"Funny Lady","genre":"Comedy|Musical","director":"Grover Spiers"},
    {"id":64,"title":"They Wait","genre":"Horror|Mystery|Thriller","director":"Kerwinn Mandeville"},
    {"id":65,"title":"Wassup Rockers","genre":"Comedy|Drama","director":"Hillie Sadat"},
    {"id":66,"title":"Coco Before Chanel (Coco avant Chanel)","genre":"Drama","director":"Lauren Philippson"},
    {"id":67,"title":"Palo Alto","genre":"Drama","director":"Audie Sparrowhawk"},
    {"id":68,"title":"Unforgettable","genre":"Mystery|Sci-Fi|Thriller","director":"Vlad Duchesne"},
    {"id":69,"title":"Malibu's Most Wanted","genre":"Comedy|Crime","director":"Claude Hammersley"},
    {"id":70,"title":"Rio","genre":"Adventure|Animation|Children|Comedy","director":"Lainey Lammers"},
    {"id":71,"title":"Forest Warrior","genre":"Action|Adventure|Comedy|Western","director":"Vikky Arkil"},
    {"id":72,"title":"Bells from the Deep","genre":"Documentary","director":"Obed Wigan"},
    {"id":73,"title":"High Cost of Living, The","genre":"Drama","director":"Ibby Kuhndel"},
    {"id":74,"title":"Barnacle Bill","genre":"Comedy|Drama","director":"Juliane Gorrissen"},
    {"id":75,"title":"Fugitive Kind, The","genre":"Crime|Drama|Romance","director":"Noreen De Bischof"},
    {"id":76,"title":"You Can't Win 'Em All","genre":"Adventure|Comedy|War","director":"Norry Dennerley"},
    {"id":77,"title":"Prestige, The","genre":"Drama|Mystery|Sci-Fi|Thriller","director":"Selle Bramble"},
    {"id":78,"title":"Ledge, The","genre":"Drama|Thriller","director":"Christian Santostefano."},
    {"id":79,"title":"Better Than Sex","genre":"Comedy|Romance","director":"Kenn Morstatt"},
    {"id":80,"title":"Amores Perros (Love's a Bitch)","genre":"Drama|Thriller","director":"Darlene Wooding"},
    {"id":81,"title":"Zack and Miri Make a Porno","genre":"Comedy|Drama|Romance","director":"Farand Obal"},
    {"id":82,"title":"Comanche Station","genre":"Western","director":"Ardenia Swaisland"},
    {"id":83,"title":"Town Without Pity","genre":"Drama","director":"Edan Flasby"},
    {"id":84,"title":"I'm Going Home (Je rentre à la maison)","genre":"Comedy|Drama","director":"Nata Kinchin"},
    {"id":85,"title":"Three Musketeers, The","genre":"Adventure|Comedy|Musical","director":"Gwen Zavattero"},
    {"id":86,"title":"Snoopy Come Home","genre":"Animation|Children|Comedy|Musical","director":"Merlina Leil"},
    {"id":87,"title":"Second in Command","genre":"Action|Thriller","director":"Kareem Glastonbury"},
    {"id":88,"title":"Hearty Paws","genre":"Adventure|Drama","director":"Stinky O'Shields"},
    {"id":89,"title":"Knightriders","genre":"Action|Adventure|Drama","director":"Sascha Allanby"},
    {"id":90,"title":"Taxi for Tobruk","genre":"Drama|War","director":"Osbourn Dragonette"},
    {"id":91,"title":"My Perestroika","genre":"Documentary","director":"Theodor Riddiford"},
    {"id":92,"title":"Courier","genre":"Comedy|Drama|Romance","director":"Darrick Wile"},
    {"id":93,"title":"Hana (Hana yori mo naho)","genre":"Comedy|Drama","director":"Hali Becarra"},
    {"id":94,"title":"And Starring Pancho Villa as Himself","genre":"Action|Comedy|Drama|War","director":"Dicky Overstall"},
    {"id":95,"title":"Man on High Heels","genre":"Action|Comedy","director":"Robenia Ewbanck"},
    {"id":96,"title":"Kicked in the Head","genre":"Comedy|Drama","director":"Josephine Howchin"},
    {"id":97,"title":"Donnie Brasco","genre":"Crime|Drama","director":"Lissie Germann"},
    {"id":98,"title":"Winnetou: The Last Shot","genre":"Action|Adventure|Western","director":"Phil Symmons"},
    {"id":99,"title":"The Menacing Eye","genre":"(no genres listed)","director":"Harli D'Hooge"},
    {"id":100,"title":"Soul Food","genre":"Drama","director":"Llewellyn Gethouse"}];

    module.exports = movieMockData;